#!/usr/bin/with-contenv sh
dir=/var/lib/https-portal/dynamic-env
mkdir -p $dir

# Remember when we started (tiny race condition window)
touch $dir.stamp # Outside of watched dir!

# Wait for a modification to an all-uppercase file (ignore temp/swp files)
inotifywait -qm -e close_write,move,delete $dir | while read line
do
	if echo "$line" | grep -q ' [_A-Z]*$'
	then
		echo "[dynamic-env] All-uppercase file modified in $dir"

		echo "[dynamic-env] Wait for activity to cease..."
		while inotifywait -qq -t 1 -e close_write,move,delete $dir
		do
			:
		done

		# Apply new configuration; but only, if anything actually
		# changed (top-level "while" loop will continue getting
		# potentially old events)
		if find $dir -newer $dir.stamp | grep -q .
		then
			# Remember when we started (tiny race condition window)
			touch $dir.stamp # Outside of watched dir!

			echo "[dynamic-env] File changed since last run: Applying new configuration..."
			/usr/bin/justc-envdir $dir /bin/reconfig
			echo "[dynamic-env] Configuration applied" >&2
		else
			echo "[dynamic-env] No file changed since last run -- suppressing"
		fi
	fi
done
