#!/bin/sh
dir=/var/lib/https-portal/dynamic-env
mkdir -p $dir

# Remember when we started (tiny race condition window)
touch $dir.stamp # Outside of watched dir!

# Wait for a modification to an all-uppercase file (ignore temp/swp files)
inotifywait -qm -e close_write,move,delete $dir | while read line
do
	if echo "$line" | grep -q ' [_A-Z]*$'
	then
		echo "[dynamic-env] All-uppercase file modified in $dir" >&2

		echo -n "[dynamic-env] Wait for activity to cease..." >&2
		while inotifywait -qq -t 1 -e close_write,move,delete $dir
		do
			echo -n . >&2
		done
		echo " -- ceased" >&2

		# Apply new configuration; but only, if anything actually
		# changed (top-level "while" loop will continue getting
		# potentially old events)
		if find $dir -newer $dir.stamp | grep -q .
		then
			# Remember when we started (tiny race condition window)
			touch $dir.stamp # Outside of watched dir!

			echo "[dynamic-env] File changed since last run: Applying new configuration..." >&2
			/usr/bin/justc-envdir $dir /bin/reconfig
			echo "[dynamic-env] Configuration applied" >&2
		else
			echo "[dynamic-env] No file changed since last run -- suppressing" >&2
		fi
	fi
done
