#!/usr/bin/with-contenv sh

docker-gen -watch -only-exposed -notify-output -notify \
	"justc-envdir -I /var/lib/https-portal/dynamic-env /bin/reconfig" \
	/etc/docker-gen/domains.tmpl /var/run/domains
